[buffs]
# This is the option to always show out of dock power for ships when they are docked. Defaults to false
use_out_of_dock_power = true

[config]
# Ignore this section, developer stuff only
assets_url_override = ''
settings_url = ''

[control]
# Enable experimental features (dev only, no effect on prood)
enable_experimental = false

# If you don't want any hotkeys you can set this to false
# (this disables both mod and scopely hotkeys)
hotkeys_enabled = true

# If you prefer to disable the extended hotkeys set this to false
hotkeys_extended = true

# If you prefer to use Scopely's hotkeys set this to true
use_scopely_hotkeys = false

[graphics]
# Allow borderless full screen mode, set to false to disable
borderless_fullscreen_f11 = true

# Set to 0.0 to disable a custom zoom, enter system at specified zoom otherwise, this doesn't work for the first time you view ANY system. But that should be fine
default_system_zoom = 1750.0

# Allow free resizing, set to false to disable
free_resize = true
# This controls the zoom speed when using Q/E in System View, defaults to 350
keyboard_zoom_speed = 350.0

# To enable addtional resolution options set this to true.
show_all_resolutions = false

# This controls how quickly the the momentum falls off when letting go of the mouse, the lower the number the quicker it stops, defaults to 0.8
system_pan_momentum_falloff = 0.8
system_pan_momentum = 0.4

# These are used for the F1-F5 zoom hotkeys
system_zoom_preset_1 = 50.0
system_zoom_preset_2 = 500.0
system_zoom_preset_3 = 1250.0
system_zoom_preset_4 = 2750.0
system_zoom_preset_5 = 5000.0

# The amount of time to spend between transitions, increase to slow transitions down
transition_time = 0.009999999776482582

# This specifies the amount to scale the UI by, 1.0 being default and anything above 1 making it larger than default, defaults to 0.9
ui_scale = 0.6

# This specifies the amount to adjust the scale by, 0.05 being default
ui_scale_adjust = 0.05

# This specifies the amount to scale the UI Object Viewers by, 1.0 being default and anything above 1 making it larger than default, defaults to 0.9
ui_scale_viewer = 1.2

# After using a zoom preset it will be set as default zoom
use_presets_as_default = true

# This controls the maximum zoom distance in System View, default is 2500.
# If you set this too a very high value the distance at which ship text labels are shown is also increased.
zoom = 5000.0

[shortcuts]
# Primary actions such as Mine or Attack or Go (SPACE bar or Mouse Right Click)
action_primary = 'SPACE|MOUSE1'

# Recall ship action (R or Mouse Side Button 2)
action_recall = 'R|MOUSE3'

# Cancel a recall operation (currently disabled due to crash)
action_recall_cancel = 'SPACE'

# Repair ship action (R or Mouse Side Button 2)
action_repair = 'R|MOUSE3'

# Secondary actions such as Scan
action_secondary = 'R'

# Switch between Cargo and Preview screens when clicked on a ship/node/station (TAB or Mouse Side Button 1)
action_secondary = 'TAB|MOUSE2'

# Toggle rewards view
action_view = 'V'

# Disable all hotkeys when using mod hotkeys
hotkeys_disble = 'CTRL-ALT-MINUS'

# Enable all hotkeys when using mod hotkeys
hotkeys_enable = 'CTRL-ALT-='

# Logging modes
log_debug = 'F9'
log_info = 'F11'
log_trace = 'SHIFT-F9'

# Fast exit the game
quit = 'F10'

# Select the Alliance tab when in chat
select_chatalliance = 'CTRL-2'

# Select the Global tab when in chat (if not disabled)
select_chatglobal = 'CTRL-1'

# Select the Private tab when in chat
select_chatprivate = 'CTRL-3'

# Locate currently selected ship
select_current = 'CTRL-SPACE'

# Select ship 1 (or locate on second press)
select_ship1 = '1'

# Select ship 2 (or locate on second press)
select_ship2 = '2'

# Select ship 3 (or locate on second press)
select_ship3 = '3'

# Select ship 4 (or locate on second press)
select_ship4 = '4'

# Select ship 5 (or locate on second press)
select_ship5 = '5'

# Select ship 6 (or locate on second press)
select_ship6 = '6'

# Select ship 7 (or locate on second press)
select_ship7 = '7'

# Select ship 8 (or locate on second press)
select_ship8 = '8'

# Set zoom presets from zoom for current session
set_zoom_default = 'CTRL-='
set_zoom_preset1 = 'SHIFT-F1'
set_zoom_preset2 = 'SHIFT-F2'
set_zoom_preset3 = 'SHIFT-F3'
set_zoom_preset4 = 'SHIFT-F4'
set_zoom_preset5 = 'SHIFT-F5'

# Show alliance screen
show_alliance = 'ALT-\'

# Show alliance armada screen
show_alliance_armada = 'CTRL-\'

# Show alliance help screen
show_alliance_help = 'SHIFT-\'

# Show artifacts screen
show_artifacts = 'SHIFT-I'

# Go to the Away Team screen
show_awayteam = 'T'

# Go to the Bookmarks screen
show_bookmarks = 'B'

# Show the chat full screen
show_chat = 'C'

# Show the chat on the left side
show_chatside1 = 'ALT-C'
show_chatside2 = '`'

# Go to the Fleet Commander screen
show_commander = 'O'

# Go to the Daily Missions tab
show_daily = 'Z'

# Go to the Events screen
show_events = 'SHIFT-E'

# Go to the Exocomp screen
show_exocomp = 'X'

# Go to the Factions screen
show_factions = 'F'

# Go to the Galaxy view
show_galaxy = 'G'

# Go to the Gifts screen
show_gifts = '/'

# Go to the Inventory screen
show_inventory = 'I'

# Go to the Missions tab
show_missions = 'M'

# Go to the Officers screen
show_officers = 'SHIFT-O'

# Go to the Q Trials screen
show_qtrials = 'SHIFT-Q'

# Go to the Refinery screen
show_refinery = 'SHIFT-F'

# Go to the Research screen
show_research = 'U'

# Go to the manage ship view
show_ships = 'N'

# Go to the Station's Exterior view
show_stationexterior = 'SHIFT-G'

# Go to the Station's Interior view
show_stationinterior = 'SHIFT-H'

# Go to the System view
show_system = 'H'

# Toggle the Armada cargo preview window
toggle_cargo_armada = 'ALT-5'

# Toggle the Default cargo preview window
toggle_cargo_default = 'ALT-1'

# Toggle the Hostile cargo preview window
toggle_cargo_hostile = 'ALT-4'

# Toggle the Player cargo preview window
toggle_cargo_player = 'ALT-2'

# Toggle the Station cargo preview window
toggle_cargo_station = 'ALT-3'

# Toggle whether locate is allowed during a preview
toggle_preview_locate = 'CTRL-R'

# Scale the UI down (shrink the HUD)
ui_scaledown = 'PGDOWN'

# Scale the UI up (expand the HUD)
ui_scaleup = 'PGUP'

# Scale the UI Object Viewer down (shrink the Object Viewer)
ui_scaleviewerdown = 'SHIFT-PGDOWN'

# Scale the UI Object Viewer up (expand the Object Viewer)
ui_scaleviewerup = 'SHIFT-PGUP'

# Adjust zoom (manual)
zoom_in = 'Q'
zoom_max = 'MINUS'
zoom_min = 'BACKSPACE'
zoom_out = 'E'
zoom_reset = '='

# Adjust zoom (presets)
zoom_preset1 = 'F1'
zoom_preset2 = 'F2'
zoom_preset3 = 'F3'
zoom_preset4 = 'F4'
zoom_preset5 = 'F5'

[sync]
# Do you want to sync battlelogs?
battlelogs = true

# Do you want to sync building data?
buildings = true

# Do you want to enable sync logging
logging = false

# Do you want to sync mission data?
missions = true

# Do you want to sync owned officer data?
officer = true

# Do you want to sync research data?
research = true

# Do you want to sync inventory data?
resources = true

# Do you want to sync owned ship data?
ships = true

# Do you want to sync owned forbidden tech data?
tech = true

# Do you want to sync trait data?
traits = true

# file = ''
# proxy = ''

###################################################
###
### Sync targets
### ============
### To use any of the following sync targets, in the given section:
###
###    1. Remove single hash and following space so
###       variable name is at start of line
###
###    2. Set the appropriate value (some may be predefined,
###       but you can still change if needed)
###
###################################################

[sync.targets.spocksclub]
### Token for auth on remote system (SpocksClub Prod)
# token = ''

### Url for remote system (SpocksClub Prod)
# url = 'https://spocks.club/sync/ingress/'

[sync.targets.nextspocksclub]
### Token for auth on remote system (SpocksClub Beta)
# token = ''

### Url for remote system (SpocksClub Beta)
# url = 'https://next.spocks.club/sync/ingress/'

[ui]
# Skip the reveal box animation, and just open the damn boxes
always_skip_reveal_sequence = true

# This setting is not used
auto_confirm_discovery = true

# Prevent 'escape' from prompting to exit the game which
# stops annoyance when hitting escape too many times out of screens
disable_escape_exit = true

# Change 'false' to 'true' from the line below to remove Galaxy Chat from the game
disable_galaxy_chat = false

# Stop locate working when ship or node previews are displayed
disable_preview_locate = true

# Stop recall working when ship or node previews are displayed
disable_preview_recall = true

# Allow suppressing configured banners (disabled_banner_types) from being displayed
# This specifies the types of Banners you DON'T want to see, This must be a comma seperated list enclosed in single quotes.
disabled_banner_types = ''

# Here is a list of POSSIBLE Banner types, I think they are relatively self-explanatory.
#
# Standard
# FactionWarning
# FactionLevelUp
# FactionLevelDown
# FactionDiscovered
# IncomingAttackFaction
# FleetBattle
# StationBattle
# Victory (Includes StationVictory)
# Defeat (Includes StationDefeat)
# Event
# ArmadaCreated
# ArmadaCanceled
# ArmadaIncomingAttack
# ArmadaBattleWon
# ArmadaBattleLost
# DiplomacyUpdated
# JoinedTakeover
# CompetitorJoinedTakeover
# AbandonedTerritory
# TakeoverVictory
# TakeoverDefeat

# Change 'false' to 'true' from the line below to extend the donation slider to max value for next Alliance level
# When max is set to 0, it will be unlimited
extend_donation_max = 2000
extend_donation_slider = true

# Set to true to always show the rewards for selected ships/stations
# These should be self-explanatory
show_armada_cargo = true
show_cargo_default = true
show_hostile_cargo = true
show_player_cargo = true
show_station_cargo = true
